CREATE DATABASE rag_db;
GRANT ALL PRIVILEGES ON DATABASE rag_db TO postgres;
CREATE DATABASE xwiki;
GRANT ALL PRIVILEGES ON DATABASE xwiki TO postgres;
CREATE DATABASE bookstack;
GRANT ALL PRIVILEGES ON DATABASE bookstack TO postgres;