ktor:
    environment: $PROFILE
    application:
        modules:
            - pl.ApplicationKt.module
    deployment:
        port: 8080
database:
  url: $DATABASE_URL
  user: $DATABASE_USER
  password: $DATABASE_PASSWORD
koog:
  api-key:
    openai:
jedis:
  host: $JEDIS_HOST
  port: $JEDIS_HOST
  password: $JEDIS_PASSWORD
xwiki:
  username: "ai"
  password: "G#m%LWz@jFAelhbW&4kCzvW63kNOsEyP"