ktor:
    application:
        modules:
            - pl.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost:15432/rag_db"
  user: postgres
  password: postgres
koog:
  api-key:
    openai: "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"
    anthropic:
jedis:
  host: "localhost"
  port: 6379
  password: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"