ktor:
    application:
        modules:
            - pl.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url:
  user:
  password:
koog:
  api-key:
    openai:
    anthropic:
jedis:
  host: "localhost"
  port: 6379
  password: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"