ktor:
    application:
        modules:
            - pl.ApplicationKt.module
    deployment:
        port: 8080
# Docker image defaults included
postgres:
  url: "jdbc:postgresql://localhost:15432/rag_db"
  user: postgres
  password: postgres
koog:
  api-key:
    openai:
jedis:
  host: "localhost"
  port: 6379
  password: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
xwiki:
  username: "ai"
  password: "G#m%LWz@jFAelhbW&4kCzvW63kNOsEyP"