apiVersion: v1
kind: Pod
metadata:
  name: ejdev
  labels:
    app: ejdev
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: ejdev-container
      image: ejdev:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
          name: http
      env:
        - name: DATABASE_URL
          value: "jdbc:postgresql://postgres:30432/rag_db"
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "postgres"
        - name: JEDIS_HOST
          value: "postgres"
        - name: JEDIS_PORT
          value: "cache"
        - name: JEDIS_PASSWORD
          value: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
#      livenessProbe:
#        httpGet:
#          path: /health
#          port: 8080
#        initialDelaySeconds: 30
#        periodSeconds: 10
#      readinessProbe:
#        httpGet:
#          path: /ready
#          port: 8080
#        initialDelaySeconds: 5
#        periodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:15
      ports:
        - containerPort: 5432
          name: postgres
      env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
      volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-storage
      emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: cache
  labels:
    app: cache
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: redis
      image: redis:6.2-alpine
      ports:
        - containerPort: 6379
          name: redis
      command:
        - redis-server
        - --save
        - "20"
        - "1"
        - --loglevel
        - warning
        - --requirepass
        - eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      volumeMounts:
        - name: cache-storage
          mountPath: /data
  volumes:
    - name: cache-storage
      emptyDir: {}